services:
  webserver:
    restart: unless-stopped
    labels:
      - traefik.http.routers.rcviriat_secure.rule=Host(`rcviriat.fr`) || Host(`www.rcviriat.fr`)
      - traefik.http.routers.rcviriat_secure.tls.certresolver=letsencrypt
      - ghosts.host=rcviriat.fr