networks:
  server_proxy:
    external: true

services:
  webserver:
    image: nginx:alpine
    networks:
      - server_proxy
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./logo.jpg:/usr/share/nginx/html/logo.jpg:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.rcviriat_secure.entrypoints=websecure
      - traefik.http.routers.rcviriat_secure.tls=true

      - ghosts.category=Websites
      - ghosts.description=Rugby Club Viriat website
      - ghosts.proto=https
